server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Service Route (Matches  /users)
# Spring Cloud Gateway Routing Configuration
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=food-service
spring.cloud.gateway.routes[1].uri=lb://FOOD-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/restaurants/**,/api/dishes/**

spring.cloud.gateway.routes[2].id=order-service
spring.cloud.gateway.routes[2].uri=lb://ORDER-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/cart/**,/api/orders/**,/api/checkout/**

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
